// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: fleet/v1/fleet.proto

package fleetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pickup        *Point                 `protobuf:"bytes,2,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *Point                 `protobuf:"bytes,3,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"` // "NAVIGATING_PICKUP", "DELIVERING", "COMPLETED"
	AssignedTo    string                 `protobuf:"bytes,7,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetPickup() *Point {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *Task) GetDropoff() *Point {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *Task) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Task) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

type RobotState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RobotId         string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	CurrentPos      *Position              `protobuf:"bytes,2,opt,name=current_pos,json=currentPos,proto3" json:"current_pos,omitempty"`
	History         []*Position            `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	IntendedPos     *Position              `protobuf:"bytes,4,opt,name=intended_pos,json=intendedPos,proto3" json:"intended_pos,omitempty"`
	TargetPos       *Position              `protobuf:"bytes,5,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	BatteryPct      float64                `protobuf:"fixed64,6,opt,name=battery_pct,json=batteryPct,proto3" json:"battery_pct,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // "IDLE", "NAVIGATING_PICKUP", "DELIVERING", "YIELDING", "REPLANNING", "OFFLINE_SIMULATED"
	CurrentTask     *Task                  `protobuf:"bytes,8,opt,name=current_task,json=currentTask,proto3" json:"current_task,omitempty"`
	TasksCompleted  int32                  `protobuf:"varint,9,opt,name=tasks_completed,json=tasksCompleted,proto3" json:"tasks_completed,omitempty"`
	Path            []*Point               `protobuf:"bytes,10,rep,name=path,proto3" json:"path,omitempty"`
	PriorityScore   int32                  `protobuf:"varint,11,opt,name=priority_score,json=priorityScore,proto3" json:"priority_score,omitempty"`
	LastHeartbeatMs int64                  `protobuf:"varint,12,opt,name=last_heartbeat_ms,json=lastHeartbeatMs,proto3" json:"last_heartbeat_ms,omitempty"`
	IsOnline        bool                   `protobuf:"varint,13,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	Port            int32                  `protobuf:"varint,14,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RobotState) Reset() {
	*x = RobotState{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotState) ProtoMessage() {}

func (x *RobotState) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotState.ProtoReflect.Descriptor instead.
func (*RobotState) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *RobotState) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *RobotState) GetCurrentPos() *Position {
	if x != nil {
		return x.CurrentPos
	}
	return nil
}

func (x *RobotState) GetHistory() []*Position {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RobotState) GetIntendedPos() *Position {
	if x != nil {
		return x.IntendedPos
	}
	return nil
}

func (x *RobotState) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *RobotState) GetBatteryPct() float64 {
	if x != nil {
		return x.BatteryPct
	}
	return 0
}

func (x *RobotState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RobotState) GetCurrentTask() *Task {
	if x != nil {
		return x.CurrentTask
	}
	return nil
}

func (x *RobotState) GetTasksCompleted() int32 {
	if x != nil {
		return x.TasksCompleted
	}
	return 0
}

func (x *RobotState) GetPath() []*Point {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *RobotState) GetPriorityScore() int32 {
	if x != nil {
		return x.PriorityScore
	}
	return 0
}

func (x *RobotState) GetLastHeartbeatMs() int64 {
	if x != nil {
		return x.LastHeartbeatMs
	}
	return 0
}

func (x *RobotState) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *RobotState) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type SyncPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sender            *RobotState            `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	YieldAcknowledged bool                   `protobuf:"varint,2,opt,name=yield_acknowledged,json=yieldAcknowledged,proto3" json:"yield_acknowledged,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncPayload) Reset() {
	*x = SyncPayload{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncPayload) ProtoMessage() {}

func (x *SyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncPayload.ProtoReflect.Descriptor instead.
func (*SyncPayload) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *SyncPayload) GetSender() *RobotState {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *SyncPayload) GetYieldAcknowledged() bool {
	if x != nil {
		return x.YieldAcknowledged
	}
	return false
}

type SyncResponsePayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Receiver          *RobotState            `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	YieldAcknowledged bool                   `protobuf:"varint,2,opt,name=yield_acknowledged,json=yieldAcknowledged,proto3" json:"yield_acknowledged,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncResponsePayload) Reset() {
	*x = SyncResponsePayload{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponsePayload) ProtoMessage() {}

func (x *SyncResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponsePayload.ProtoReflect.Descriptor instead.
func (*SyncResponsePayload) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponsePayload) GetReceiver() *RobotState {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *SyncResponsePayload) GetYieldAcknowledged() bool {
	if x != nil {
		return x.YieldAcknowledged
	}
	return false
}

type DashboardCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandType   string                 `protobuf:"bytes,1,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"` // "DISPATCH_TASK", "BLOCK_AISLE", "CLEAR_AISLES", "TOGGLE_POWER", "SET_MODE"
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	BlockX        float64                `protobuf:"fixed64,3,opt,name=block_x,json=blockX,proto3" json:"block_x,omitempty"`
	BlockY        float64                `protobuf:"fixed64,4,opt,name=block_y,json=blockY,proto3" json:"block_y,omitempty"`
	Enable        bool                   `protobuf:"varint,5,opt,name=enable,proto3" json:"enable,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	TargetRobotId string                 `protobuf:"bytes,7,opt,name=target_robot_id,json=targetRobotId,proto3" json:"target_robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardCommand) Reset() {
	*x = DashboardCommand{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardCommand) ProtoMessage() {}

func (x *DashboardCommand) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardCommand.ProtoReflect.Descriptor instead.
func (*DashboardCommand) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *DashboardCommand) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *DashboardCommand) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *DashboardCommand) GetBlockX() float64 {
	if x != nil {
		return x.BlockX
	}
	return 0
}

func (x *DashboardCommand) GetBlockY() float64 {
	if x != nil {
		return x.BlockY
	}
	return 0
}

func (x *DashboardCommand) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *DashboardCommand) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *DashboardCommand) GetTargetRobotId() string {
	if x != nil {
		return x.TargetRobotId
	}
	return ""
}

type FleetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetTelemetryRequest) Reset() {
	*x = FleetTelemetryRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetTelemetryRequest) ProtoMessage() {}

func (x *FleetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*FleetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *FleetTelemetryRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type FleetTelemetry struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Robots              map[string]*RobotState `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tasks               []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	PotentialCollisions int32                  `protobuf:"varint,3,opt,name=potential_collisions,json=potentialCollisions,proto3" json:"potential_collisions,omitempty"`
	TotalTasksCompleted int32                  `protobuf:"varint,4,opt,name=total_tasks_completed,json=totalTasksCompleted,proto3" json:"total_tasks_completed,omitempty"`
	Mode                string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	Logs                []string               `protobuf:"bytes,6,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FleetTelemetry) Reset() {
	*x = FleetTelemetry{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetTelemetry) ProtoMessage() {}

func (x *FleetTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetTelemetry.ProtoReflect.Descriptor instead.
func (*FleetTelemetry) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *FleetTelemetry) GetRobots() map[string]*RobotState {
	if x != nil {
		return x.Robots
	}
	return nil
}

func (x *FleetTelemetry) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *FleetTelemetry) GetPotentialCollisions() int32 {
	if x != nil {
		return x.PotentialCollisions
	}
	return 0
}

func (x *FleetTelemetry) GetTotalTasksCompleted() int32 {
	if x != nil {
		return x.TotalTasksCompleted
	}
	return 0
}

func (x *FleetTelemetry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FleetTelemetry) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type AssignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskRequest) Reset() {
	*x = AssignTaskRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskRequest) ProtoMessage() {}

func (x *AssignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskRequest.ProtoReflect.Descriptor instead.
func (*AssignTaskRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *AssignTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type AssignTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RobotId       string                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTaskResponse) Reset() {
	*x = AssignTaskResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTaskResponse) ProtoMessage() {}

func (x *AssignTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTaskResponse.ProtoReflect.Descriptor instead.
func (*AssignTaskResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *AssignTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AssignTaskResponse) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *AssignTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ToggleNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	BlockAisle    bool                   `protobuf:"varint,3,opt,name=block_aisle,json=blockAisle,proto3" json:"block_aisle,omitempty"`
	BlockedX      float64                `protobuf:"fixed64,4,opt,name=blocked_x,json=blockedX,proto3" json:"blocked_x,omitempty"`
	BlockedY      float64                `protobuf:"fixed64,5,opt,name=blocked_y,json=blockedY,proto3" json:"blocked_y,omitempty"`
	Mode          string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleNodeRequest) Reset() {
	*x = ToggleNodeRequest{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleNodeRequest) ProtoMessage() {}

func (x *ToggleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleNodeRequest.ProtoReflect.Descriptor instead.
func (*ToggleNodeRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *ToggleNodeRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *ToggleNodeRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ToggleNodeRequest) GetBlockAisle() bool {
	if x != nil {
		return x.BlockAisle
	}
	return false
}

func (x *ToggleNodeRequest) GetBlockedX() float64 {
	if x != nil {
		return x.BlockedX
	}
	return 0
}

func (x *ToggleNodeRequest) GetBlockedY() float64 {
	if x != nil {
		return x.BlockedY
	}
	return 0
}

func (x *ToggleNodeRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ToggleNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleNodeResponse) Reset() {
	*x = ToggleNodeResponse{}
	mi := &file_fleet_v1_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleNodeResponse) ProtoMessage() {}

func (x *ToggleNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleNodeResponse.ProtoReflect.Descriptor instead.
func (*ToggleNodeResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleNodeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_fleet_v1_fleet_proto protoreflect.FileDescriptor

const file_fleet_v1_fleet_proto_rawDesc = "" +
	"\n" +
	"\x14fleet/v1/fleet.proto\x12\bfleet.v1\"I\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xde\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x06pickup\x18\x02 \x01(\v2\x0f.fleet.v1.PointR\x06pickup\x12)\n" +
	"\adropoff\x18\x03 \x01(\v2\x0f.fleet.v1.PointR\adropoff\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vassigned_to\x18\a \x01(\tR\n" +
	"assignedTo\"\xb2\x04\n" +
	"\n" +
	"RobotState\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x123\n" +
	"\vcurrent_pos\x18\x02 \x01(\v2\x12.fleet.v1.PositionR\n" +
	"currentPos\x12,\n" +
	"\ahistory\x18\x03 \x03(\v2\x12.fleet.v1.PositionR\ahistory\x125\n" +
	"\fintended_pos\x18\x04 \x01(\v2\x12.fleet.v1.PositionR\vintendedPos\x121\n" +
	"\n" +
	"target_pos\x18\x05 \x01(\v2\x12.fleet.v1.PositionR\ttargetPos\x12\x1f\n" +
	"\vbattery_pct\x18\x06 \x01(\x01R\n" +
	"batteryPct\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x121\n" +
	"\fcurrent_task\x18\b \x01(\v2\x0e.fleet.v1.TaskR\vcurrentTask\x12'\n" +
	"\x0ftasks_completed\x18\t \x01(\x05R\x0etasksCompleted\x12#\n" +
	"\x04path\x18\n" +
	" \x03(\v2\x0f.fleet.v1.PointR\x04path\x12%\n" +
	"\x0epriority_score\x18\v \x01(\x05R\rpriorityScore\x12*\n" +
	"\x11last_heartbeat_ms\x18\f \x01(\x03R\x0flastHeartbeatMs\x12\x1b\n" +
	"\tis_online\x18\r \x01(\bR\bisOnline\x12\x12\n" +
	"\x04port\x18\x0e \x01(\x05R\x04port\"j\n" +
	"\vSyncPayload\x12,\n" +
	"\x06sender\x18\x01 \x01(\v2\x14.fleet.v1.RobotStateR\x06sender\x12-\n" +
	"\x12yield_acknowledged\x18\x02 \x01(\bR\x11yieldAcknowledged\"v\n" +
	"\x13SyncResponsePayload\x120\n" +
	"\breceiver\x18\x01 \x01(\v2\x14.fleet.v1.RobotStateR\breceiver\x12-\n" +
	"\x12yield_acknowledged\x18\x02 \x01(\bR\x11yieldAcknowledged\"\xdf\x01\n" +
	"\x10DashboardCommand\x12!\n" +
	"\fcommand_type\x18\x01 \x01(\tR\vcommandType\x12\"\n" +
	"\x04task\x18\x02 \x01(\v2\x0e.fleet.v1.TaskR\x04task\x12\x17\n" +
	"\ablock_x\x18\x03 \x01(\x01R\x06blockX\x12\x17\n" +
	"\ablock_y\x18\x04 \x01(\x01R\x06blockY\x12\x16\n" +
	"\x06enable\x18\x05 \x01(\bR\x06enable\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12&\n" +
	"\x0ftarget_robot_id\x18\a \x01(\tR\rtargetRobotId\"4\n" +
	"\x15FleetTelemetryRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xd4\x02\n" +
	"\x0eFleetTelemetry\x12<\n" +
	"\x06robots\x18\x01 \x03(\v2$.fleet.v1.FleetTelemetry.RobotsEntryR\x06robots\x12$\n" +
	"\x05tasks\x18\x02 \x03(\v2\x0e.fleet.v1.TaskR\x05tasks\x121\n" +
	"\x14potential_collisions\x18\x03 \x01(\x05R\x13potentialCollisions\x122\n" +
	"\x15total_tasks_completed\x18\x04 \x01(\x05R\x13totalTasksCompleted\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x12\n" +
	"\x04logs\x18\x06 \x03(\tR\x04logs\x1aO\n" +
	"\vRobotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.fleet.v1.RobotStateR\x05value:\x028\x01\"7\n" +
	"\x11AssignTaskRequest\x12\"\n" +
	"\x04task\x18\x01 \x01(\v2\x0e.fleet.v1.TaskR\x04task\"k\n" +
	"\x12AssignTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\tR\arobotId\x12\"\n" +
	"\x04task\x18\x03 \x01(\v2\x0e.fleet.v1.TaskR\x04task\"\xb5\x01\n" +
	"\x11ToggleNodeRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\x12\x1f\n" +
	"\vblock_aisle\x18\x03 \x01(\bR\n" +
	"blockAisle\x12\x1b\n" +
	"\tblocked_x\x18\x04 \x01(\x01R\bblockedX\x12\x1b\n" +
	"\tblocked_y\x18\x05 \x01(\x01R\bblockedY\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\",\n" +
	"\x12ToggleNodeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xc0\x02\n" +
	"\fFleetService\x12I\n" +
	"\rStreamP2PMesh\x12\x15.fleet.v1.SyncPayload\x1a\x1d.fleet.v1.SyncResponsePayload(\x010\x01\x12S\n" +
	"\x14StreamFleetTelemetry\x12\x1f.fleet.v1.FleetTelemetryRequest\x1a\x18.fleet.v1.FleetTelemetry0\x01\x12G\n" +
	"\n" +
	"AssignTask\x12\x1b.fleet.v1.AssignTaskRequest\x1a\x1c.fleet.v1.AssignTaskResponse\x12G\n" +
	"\n" +
	"ToggleNode\x12\x1b.fleet.v1.ToggleNodeRequest\x1a\x1c.fleet.v1.ToggleNodeResponseB*Z(sih-amr-fleet/pkg/proto/fleet/v1;fleetv1b\x06proto3"

var (
	file_fleet_v1_fleet_proto_rawDescOnce sync.Once
	file_fleet_v1_fleet_proto_rawDescData []byte
)

func file_fleet_v1_fleet_proto_rawDescGZIP() []byte {
	file_fleet_v1_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_v1_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)))
	})
	return file_fleet_v1_fleet_proto_rawDescData
}

var file_fleet_v1_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_fleet_v1_fleet_proto_goTypes = []any{
	(*Position)(nil),              // 0: fleet.v1.Position
	(*Point)(nil),                 // 1: fleet.v1.Point
	(*Task)(nil),                  // 2: fleet.v1.Task
	(*RobotState)(nil),            // 3: fleet.v1.RobotState
	(*SyncPayload)(nil),           // 4: fleet.v1.SyncPayload
	(*SyncResponsePayload)(nil),   // 5: fleet.v1.SyncResponsePayload
	(*DashboardCommand)(nil),      // 6: fleet.v1.DashboardCommand
	(*FleetTelemetryRequest)(nil), // 7: fleet.v1.FleetTelemetryRequest
	(*FleetTelemetry)(nil),        // 8: fleet.v1.FleetTelemetry
	(*AssignTaskRequest)(nil),     // 9: fleet.v1.AssignTaskRequest
	(*AssignTaskResponse)(nil),    // 10: fleet.v1.AssignTaskResponse
	(*ToggleNodeRequest)(nil),     // 11: fleet.v1.ToggleNodeRequest
	(*ToggleNodeResponse)(nil),    // 12: fleet.v1.ToggleNodeResponse
	nil,                           // 13: fleet.v1.FleetTelemetry.RobotsEntry
}
var file_fleet_v1_fleet_proto_depIdxs = []int32{
	1,  // 0: fleet.v1.Task.pickup:type_name -> fleet.v1.Point
	1,  // 1: fleet.v1.Task.dropoff:type_name -> fleet.v1.Point
	0,  // 2: fleet.v1.RobotState.current_pos:type_name -> fleet.v1.Position
	0,  // 3: fleet.v1.RobotState.history:type_name -> fleet.v1.Position
	0,  // 4: fleet.v1.RobotState.intended_pos:type_name -> fleet.v1.Position
	0,  // 5: fleet.v1.RobotState.target_pos:type_name -> fleet.v1.Position
	2,  // 6: fleet.v1.RobotState.current_task:type_name -> fleet.v1.Task
	1,  // 7: fleet.v1.RobotState.path:type_name -> fleet.v1.Point
	3,  // 8: fleet.v1.SyncPayload.sender:type_name -> fleet.v1.RobotState
	3,  // 9: fleet.v1.SyncResponsePayload.receiver:type_name -> fleet.v1.RobotState
	2,  // 10: fleet.v1.DashboardCommand.task:type_name -> fleet.v1.Task
	13, // 11: fleet.v1.FleetTelemetry.robots:type_name -> fleet.v1.FleetTelemetry.RobotsEntry
	2,  // 12: fleet.v1.FleetTelemetry.tasks:type_name -> fleet.v1.Task
	2,  // 13: fleet.v1.AssignTaskRequest.task:type_name -> fleet.v1.Task
	2,  // 14: fleet.v1.AssignTaskResponse.task:type_name -> fleet.v1.Task
	3,  // 15: fleet.v1.FleetTelemetry.RobotsEntry.value:type_name -> fleet.v1.RobotState
	4,  // 16: fleet.v1.FleetService.StreamP2PMesh:input_type -> fleet.v1.SyncPayload
	7,  // 17: fleet.v1.FleetService.StreamFleetTelemetry:input_type -> fleet.v1.FleetTelemetryRequest
	9,  // 18: fleet.v1.FleetService.AssignTask:input_type -> fleet.v1.AssignTaskRequest
	11, // 19: fleet.v1.FleetService.ToggleNode:input_type -> fleet.v1.ToggleNodeRequest
	5,  // 20: fleet.v1.FleetService.StreamP2PMesh:output_type -> fleet.v1.SyncResponsePayload
	8,  // 21: fleet.v1.FleetService.StreamFleetTelemetry:output_type -> fleet.v1.FleetTelemetry
	10, // 22: fleet.v1.FleetService.AssignTask:output_type -> fleet.v1.AssignTaskResponse
	12, // 23: fleet.v1.FleetService.ToggleNode:output_type -> fleet.v1.ToggleNodeResponse
	20, // [20:24] is the sub-list for method output_type
	16, // [16:20] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_fleet_v1_fleet_proto_init() }
func file_fleet_v1_fleet_proto_init() {
	if File_fleet_v1_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_fleet_proto_rawDesc), len(file_fleet_v1_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_v1_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_v1_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_v1_fleet_proto_msgTypes,
	}.Build()
	File_fleet_v1_fleet_proto = out.File
	file_fleet_v1_fleet_proto_goTypes = nil
	file_fleet_v1_fleet_proto_depIdxs = nil
}
