// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: fleet/v1/fleet.proto

package fleetv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sih-amr-fleet/pkg/proto/fleet/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FleetServiceName is the fully-qualified name of the FleetService service.
	FleetServiceName = "fleet.v1.FleetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FleetServiceStreamP2PMeshProcedure is the fully-qualified name of the FleetService's
	// StreamP2PMesh RPC.
	FleetServiceStreamP2PMeshProcedure = "/fleet.v1.FleetService/StreamP2PMesh"
	// FleetServiceStreamFleetTelemetryProcedure is the fully-qualified name of the FleetService's
	// StreamFleetTelemetry RPC.
	FleetServiceStreamFleetTelemetryProcedure = "/fleet.v1.FleetService/StreamFleetTelemetry"
	// FleetServiceAssignTaskProcedure is the fully-qualified name of the FleetService's AssignTask RPC.
	FleetServiceAssignTaskProcedure = "/fleet.v1.FleetService/AssignTask"
	// FleetServiceToggleNodeProcedure is the fully-qualified name of the FleetService's ToggleNode RPC.
	FleetServiceToggleNodeProcedure = "/fleet.v1.FleetService/ToggleNode"
)

// FleetServiceClient is a client for the fleet.v1.FleetService service.
type FleetServiceClient interface {
	// Bi-directional 10Hz stream for P2P inter-robot mesh over HTTP/3 QUIC
	StreamP2PMesh(context.Context) *connect.BidiStreamForClient[v1.SyncPayload, v1.SyncResponsePayload]
	// 10Hz Server Streaming RPC for React Dashboard (Telemetry Downstream)
	StreamFleetTelemetry(context.Context, *connect.Request[v1.FleetTelemetryRequest]) (*connect.ServerStreamForClient[v1.FleetTelemetry], error)
	// Unary fallback RPCs
	AssignTask(context.Context, *connect.Request[v1.AssignTaskRequest]) (*connect.Response[v1.AssignTaskResponse], error)
	ToggleNode(context.Context, *connect.Request[v1.ToggleNodeRequest]) (*connect.Response[v1.ToggleNodeResponse], error)
}

// NewFleetServiceClient constructs a client for the fleet.v1.FleetService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFleetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FleetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fleetServiceMethods := v1.File_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	return &fleetServiceClient{
		streamP2PMesh: connect.NewClient[v1.SyncPayload, v1.SyncResponsePayload](
			httpClient,
			baseURL+FleetServiceStreamP2PMeshProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("StreamP2PMesh")),
			connect.WithClientOptions(opts...),
		),
		streamFleetTelemetry: connect.NewClient[v1.FleetTelemetryRequest, v1.FleetTelemetry](
			httpClient,
			baseURL+FleetServiceStreamFleetTelemetryProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("StreamFleetTelemetry")),
			connect.WithClientOptions(opts...),
		),
		assignTask: connect.NewClient[v1.AssignTaskRequest, v1.AssignTaskResponse](
			httpClient,
			baseURL+FleetServiceAssignTaskProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("AssignTask")),
			connect.WithClientOptions(opts...),
		),
		toggleNode: connect.NewClient[v1.ToggleNodeRequest, v1.ToggleNodeResponse](
			httpClient,
			baseURL+FleetServiceToggleNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ToggleNode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fleetServiceClient implements FleetServiceClient.
type fleetServiceClient struct {
	streamP2PMesh        *connect.Client[v1.SyncPayload, v1.SyncResponsePayload]
	streamFleetTelemetry *connect.Client[v1.FleetTelemetryRequest, v1.FleetTelemetry]
	assignTask           *connect.Client[v1.AssignTaskRequest, v1.AssignTaskResponse]
	toggleNode           *connect.Client[v1.ToggleNodeRequest, v1.ToggleNodeResponse]
}

// StreamP2PMesh calls fleet.v1.FleetService.StreamP2PMesh.
func (c *fleetServiceClient) StreamP2PMesh(ctx context.Context) *connect.BidiStreamForClient[v1.SyncPayload, v1.SyncResponsePayload] {
	return c.streamP2PMesh.CallBidiStream(ctx)
}

// StreamFleetTelemetry calls fleet.v1.FleetService.StreamFleetTelemetry.
func (c *fleetServiceClient) StreamFleetTelemetry(ctx context.Context, req *connect.Request[v1.FleetTelemetryRequest]) (*connect.ServerStreamForClient[v1.FleetTelemetry], error) {
	return c.streamFleetTelemetry.CallServerStream(ctx, req)
}

// AssignTask calls fleet.v1.FleetService.AssignTask.
func (c *fleetServiceClient) AssignTask(ctx context.Context, req *connect.Request[v1.AssignTaskRequest]) (*connect.Response[v1.AssignTaskResponse], error) {
	return c.assignTask.CallUnary(ctx, req)
}

// ToggleNode calls fleet.v1.FleetService.ToggleNode.
func (c *fleetServiceClient) ToggleNode(ctx context.Context, req *connect.Request[v1.ToggleNodeRequest]) (*connect.Response[v1.ToggleNodeResponse], error) {
	return c.toggleNode.CallUnary(ctx, req)
}

// FleetServiceHandler is an implementation of the fleet.v1.FleetService service.
type FleetServiceHandler interface {
	// Bi-directional 10Hz stream for P2P inter-robot mesh over HTTP/3 QUIC
	StreamP2PMesh(context.Context, *connect.BidiStream[v1.SyncPayload, v1.SyncResponsePayload]) error
	// 10Hz Server Streaming RPC for React Dashboard (Telemetry Downstream)
	StreamFleetTelemetry(context.Context, *connect.Request[v1.FleetTelemetryRequest], *connect.ServerStream[v1.FleetTelemetry]) error
	// Unary fallback RPCs
	AssignTask(context.Context, *connect.Request[v1.AssignTaskRequest]) (*connect.Response[v1.AssignTaskResponse], error)
	ToggleNode(context.Context, *connect.Request[v1.ToggleNodeRequest]) (*connect.Response[v1.ToggleNodeResponse], error)
}

// NewFleetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFleetServiceHandler(svc FleetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fleetServiceMethods := v1.File_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	fleetServiceStreamP2PMeshHandler := connect.NewBidiStreamHandler(
		FleetServiceStreamP2PMeshProcedure,
		svc.StreamP2PMesh,
		connect.WithSchema(fleetServiceMethods.ByName("StreamP2PMesh")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceStreamFleetTelemetryHandler := connect.NewServerStreamHandler(
		FleetServiceStreamFleetTelemetryProcedure,
		svc.StreamFleetTelemetry,
		connect.WithSchema(fleetServiceMethods.ByName("StreamFleetTelemetry")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceAssignTaskHandler := connect.NewUnaryHandler(
		FleetServiceAssignTaskProcedure,
		svc.AssignTask,
		connect.WithSchema(fleetServiceMethods.ByName("AssignTask")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceToggleNodeHandler := connect.NewUnaryHandler(
		FleetServiceToggleNodeProcedure,
		svc.ToggleNode,
		connect.WithSchema(fleetServiceMethods.ByName("ToggleNode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/fleet.v1.FleetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FleetServiceStreamP2PMeshProcedure:
			fleetServiceStreamP2PMeshHandler.ServeHTTP(w, r)
		case FleetServiceStreamFleetTelemetryProcedure:
			fleetServiceStreamFleetTelemetryHandler.ServeHTTP(w, r)
		case FleetServiceAssignTaskProcedure:
			fleetServiceAssignTaskHandler.ServeHTTP(w, r)
		case FleetServiceToggleNodeProcedure:
			fleetServiceToggleNodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFleetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFleetServiceHandler struct{}

func (UnimplementedFleetServiceHandler) StreamP2PMesh(context.Context, *connect.BidiStream[v1.SyncPayload, v1.SyncResponsePayload]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("fleet.v1.FleetService.StreamP2PMesh is not implemented"))
}

func (UnimplementedFleetServiceHandler) StreamFleetTelemetry(context.Context, *connect.Request[v1.FleetTelemetryRequest], *connect.ServerStream[v1.FleetTelemetry]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("fleet.v1.FleetService.StreamFleetTelemetry is not implemented"))
}

func (UnimplementedFleetServiceHandler) AssignTask(context.Context, *connect.Request[v1.AssignTaskRequest]) (*connect.Response[v1.AssignTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fleet.v1.FleetService.AssignTask is not implemented"))
}

func (UnimplementedFleetServiceHandler) ToggleNode(context.Context, *connect.Request[v1.ToggleNodeRequest]) (*connect.Response[v1.ToggleNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("fleet.v1.FleetService.ToggleNode is not implemented"))
}
